name: ğŸš¢ SFTP Deployment ğŸš¢

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¨ Checkout repository ğŸ“¨
        uses: actions/checkout@v2

      - name: ğŸ“ Install Node.js and npm ğŸ“
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: ğŸ“¥ Install dependencies ğŸ“¥
        run: npm install

      - name: ğŸ“¦ Build project ğŸ“¦
        run: npm run build
        
      - name: ğŸ§¹ Delete index.html from dist ğŸ§¹
        run: rm ./dist/index.html

      - name: ğŸš€ Upload dist ğŸš€ via SFTP ğŸ”‘
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_STRATO_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: "./dist"
          remote_path: "StudioWebsite/"
